# ===============================================
# Properties de fallback - Configurações em comum
# ===============================================
spring.application.name=faturamento-manager-api

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/faturamento-manager
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update